[build]
  command = "npm run build"
  publish = "client/build"

[site]
  base = "client" # If your client code is in a subdirectory

[build.environment]
  REACT_APP_API_URL = "/.netlify/functions/server"

[functions]
  directory = "server/functions"
